version: '2'
services:
  php:
    image: php:8.2-apache
    container_name: aldrin_sertifikasi
    volumes:
      - ./:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - mysql
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000

  mysql:
    image: mysql:8
    container_name: db_aldrin_native
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root123"
      MYSQL_DATABASE: db_aldrin
      MYSQL_USER: root
      MYSQL_PASSWORD: "root123"
    ports:
      - '3307:3306'
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_native
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: "root123"

volumes:
  mysql_data:
